### PR TITLE
updating metrics core version to fix graphite

### PR DESCRIPTION
**Pull request by DustinChaloupka**

### CODE REVIEW

**Comment by nicgrayson** [comment]
This is to fix this issue we were experiencing: https://github.com/dropwizard/metrics/issues/694

**Comment by adamdecaf** [comment]
I don't see a '3.1.2-java7' Do we need to release that to our nexus? https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.dropwizard.metrics%22%20AND%20a%3A%22metrics-core%22 Or did they release it?

**Comment by adamdecaf** [comment]
So since https://github.com/dropwizard/metrics/pull/757 was commited to their master branch, and not the 3.1-maintenance branch we probably need to update from theirs and cherry-pick this over there?

**Comment by DustinChaloupka** [comment]
@adamdecaf It is on Nexus.

**Comment by adamdecaf** [comment]
retest this please

**Comment by rubbish** [comment]
PR build failed with:
```
[info] [0m[[33mwarn[0m] [0m	[NOT FOUND  ] io.dropwizard.metrics#metrics-core;3.1.2-java7!metrics-core.jar(bundle) (0ms)[0m
```

**Comment by adamdecaf** [comment]
It was published to our "3rd Party" repository.

http://nexus.banno.com/nexus/index.html#view-repositories;thirdparty~browsestorage~/io/dropwizard/metrics/metrics-core/3.1.2-java7/metrics-core-3.1.2-java7.pom

https://github.com/Banno/banno-sbt-plugin/commit/5413f058e7e73c3c37fb91db6b0a1860c8ed1ba8 should fix it now.

**Comment by zcox** [comment]
:+1:

**Comment by rubbish** [comment]
https://github.com/Banno/banno-sbt-plugin/commit/5413f058e7e73c3c37fb91db6b0a1860c8ed1ba8 shouldn't be necessary since http://nexus.banno.com/nexus/index.html#view-repositories;external~configuration contains the thirdparty. So maybe its cache needs cleared?

**Comment by rubbish** [comment]
It being the external repo

**Comment by adamdecaf** [comment]
"3rd Party Snapshots" was part of it, but not "3rd Party" (where this was published).

**Comment by rubbish** [comment]
hmm... http://nexus.banno.com/nexus/content/groups/external/io/dropwizard/metrics/metrics-core/ doesn't seem to be showing the new version.......

**Comment by adamdecaf** [comment]
Do we have to clear a cache for it to re-index the version?

**Comment by adamdecaf** [comment]
So it looks like somehow we got it partially published. http://nexus.banno.com/nexus/content/repositories/thirdparty/io/dropwizard/metrics/metrics-core/3.1.2-java7/ only has the .poms

**Comment by adamdecaf** [comment]
retest this please

**Comment by adamdecaf** [comment]
So I uploaded https://github.com/dropwizard/metrics/compare/3.1-maintenance...Banno:3.1-maintenance to nexus, let's see how this works out now.

**Comment by adamdecaf** [comment]
retest this please

**Comment by adamdecaf** [comment]
Alright, does this look good now to everyone?

**Pull request merged**
