### PR TITLE
go around nginx for nexus interactions

### PR DESCRIPTION
**Pull request by rubbish**
This is because nginx was corrupting some jxchange-scalaxb uploads. I've verified by going around nginx, the jar's MD5 and SHA1 checksums remain intact.

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
:+1:

**Comment by adamdecaf** [comment]
:+1: Is this just a temporary fix?

**Comment by rubbish** [comment]
@adamdecaf I'm leaning towards keeping it this. I can't run nexus on port 80 without running nexus as root, which nexus doesn't like either.

Nexus has been running on port 8081 forever.

**Comment by DustinChaloupka** [comment]
This needs merged and published for the scalaxb release jobs on jenkins.

**Comment by adamdecaf** [comment]
@rubbish @DustinChaloupka running under https://jenkins.dev.banno-internal.com/job/banno-sbt-plugin/154/console

**Pull request merged**
