### PR TITLE
Upgrade sbt-assembly to 0.14.2

### PR DESCRIPTION
**Pull request by zcox**
tldr I need the new [shade](https://github.com/sbt/sbt-assembly#shading) features in sbt-assembly 0.14.2 for https://github.com/Banno/kernel/issues/83.

sbt-assembly moved around some things, so this will break the [build.sbt of every project that uses it](https://github.com/search?p=2&q=user%3Abanno+sbtassembly&type=Code&utf8=%E2%9C%93). However, it should be trivial to fix these - just have to fix imports in build.sbt. I can PR these projects.

### CODE REVIEW

**Comment by adamdecaf** [comment]
:+1:

**Comment by zcox** [comment]
https://github.com/Banno/core-fetch/pull/505 is an example of the minimal project build.sbt changes.

**Comment by sherzberg** [comment]
:+1: i like upgrading things

**Comment by zcox** [comment]
All projects that this broke should now be fixed and PR'd.

**Comment by hoff2** [comment]
:+1: "and I like sayin' 'aye'!" http://spongebob.wikia.com/wiki/SpongeBob's_Last_Stand_(transcript)

**Pull request merged**
