### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by adamdecaf**
Gah, I messed up the branches and https://github.com/Banno/banno-sbt-plugin/pull/85 will need to be merged first.

### CODE REVIEW

**Comment by jwinder** [comment]
Looks good

**Comment by adamdecaf** [comment]
Changed a couple things around.

**Comment by adamdecaf** [comment]
You can view it [rendered](https://github.com/Banno/banno-sbt-plugin/blob/add-changelog/CHANGELOG.md) also.

**Comment by adamdecaf** [comment]
This is g2g now.

**Pull request merged**
