### PR TITLE
Run gulp tasks

### PR DESCRIPTION
**Pull request by eheikes**
UX is starting to use gulp as a task runner (instead of grunt), so we'll want to have sbt run `gulp default` instead of `grunt default` for projects that have been converted to gulp.

### CODE REVIEW

**Comment by adamdecaf** [comment]
:+1: Any chance we could add a test project that uses gulp in the sbt-scripted tests?

**Comment by eheikes** [comment]
@adamdecaf Sure, but are tests even used? `sbt test` fails for me.

**Comment by adamdecaf** [comment]
@eheikes They're ran via "sbt scripted" in this project.

**Comment by eheikes** [comment]
Tests don't pass with `sbt scripted` either... http://pastebin.com/TYBh1gpu

**Comment by adamdecaf** [comment]
@eheikes What are your java memory args like when you run sbt? (There's a `java.lang.OutOfMemoryError: PermGen space` in that gist) I give sbt more than the default. 

```
/usr/bin/java -Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -jar /Users/adam/.sbt/launchers/0.13.6/sbt-launch.jar shell
```

**Comment by eheikes** [comment]
I don't have an `sbt-launch.jar` in my `.sbt` folder, so I'm not sure how to proceed. If this project requires fiddly settings beyond a stock JRE, then can instructions be added somewhere?

**Comment by adamdecaf** [comment]
@eheikes I think it's just the setting that are configured with how you have `sbt` installed. Did you install sbt with brew?

**Comment by eheikes** [comment]
@adamdecaf It's the homebrew sbt. I tried setting an `SBT_OPTS` env variable as recommended by the brew package, but that didn't help:

```shell
export SBT_OPTS="-Xms512m -Xmx1536m -Xss2m -XX:ReservedCodeCacheSize=256m -XX:+TieredCompilation -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"
```

**Comment by adamdecaf** [comment]
@eheikes Did you restart sbt after applying those? You can check that it's applied with `ps aux | grep sbt` and find it in the list.

**Comment by eheikes** [comment]
@adamdecaf Yeah, no sbt is running after I set the env var and rerun `sbt scripted`. Same java.lang.OutOfMemoryError error.

**Comment by adamdecaf** [comment]
Hey @eheikes I bumped some of the memory settings for scripted. Could you try to run the `sbt scripted` task again on your machine?

**Comment by eheikes** [comment]
@adamdecaf Sorry, no change. I pulled the latest master and tried again and got the same errors.

**Comment by eheikes** [comment]
I upgraded to Java 1.8 and the problem has gone away (though the multi-project test still causes a NullPointerException).

**Comment by adamdecaf** [comment]
@eheikes Could you gist the exception that's being thrown?

**Comment by eheikes** [comment]
@adamdecaf does this work? http://pastebin.com/frLnBpjk

**Comment by adamdecaf** [comment]
@eheikes You might not have nexus credentials for that test.

**Comment by adamdecaf** [comment]
@eheikes Do you have a sample gulpfile we could add into the 'js test' scripted test?

**Comment by eheikes** [comment]
@adamdecaf Yeah. I was going to try putting something together when I had some time.

**Comment by eheikes** [comment]
I added a gulpfile and the module to the JS test. I don't know what to do next... it fails with a "permission denied" error. I can't find any good documentation on sbt scripted.

**Comment by adamdecaf** [comment]
:+1:

**Pull request merged**
