### PR TITLE
Update test dependencies to recent versions

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
The test dependencies were very out of date. In addition, bower and the grunt-cli should be globally installed - not locally. Removing those from the dependencies.

### CODE REVIEW

**Comment by adamdecaf** [comment]
:+1:

**Comment by zcox** [comment]
:+1:

**Comment by ChadKillingsworth** [comment]
retest this please

**Comment by zcox** [comment]
retest this please

**Comment by zcox** [comment]
This should also probably go on 8-SNAPSHOT, yeah?

**Comment by DustinChaloupka** [comment]
:+1: @zcox Master is 8-SNAPSHOT so this can just be merged in if the build passes.

**Pull request merged**
