### PR TITLE
updating to sbt-docker v1.1

### PR DESCRIPTION
**Pull request by rubbish**
This simplifies a lot of things.

I'll fix up sidecar next.

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
So the tests will not pass because of the slaves being on docker 1.2.0 still (not sure when `--pull` became available).  Ran them locally and it was fine. :+1:

**Comment by rubbish** [comment]
@DustinChaloupka i'll remove the --pull part for now and make a note to re-enable it once slaves have been updated

**Comment by rubbish** [comment]
@DustinChaloupka okay, looks like we might have to upgrade or jenkins-slaves anyways....... I'm going to revert out that change of mine.

**Comment by DustinChaloupka** [comment]
retest this please

**Comment by DustinChaloupka** [comment]
She good :+1:

**Pull request merged**
