### PR TITLE
Set `crossVersions` to the current `scalaVersion`

### PR DESCRIPTION
**Pull request by DustinChaloupka**
The sbt release project tries to release across all given scala versions if [certain values are set](https://github.com/sbt/sbt-release/blob/ffa6012439f85dfd34f3aeef0b7e268d6bf100d6/README.md#cross-building-during-a-release) which was causing some problems. This changes it to just default the value to the current `scalaVersion` value.

This also includes a minor fix to destroy all given big services instead of just the first one given to the function.

### CODE REVIEW

**Comment by adamdecaf** [comment]
I thought https://github.com/Banno/big/pull/214 fixed the issue in https://github.com/Banno/banno-sbt-plugin/commit/ac04c51ac7b3d4e19aa177acebb6b5eea0a7f8ec

**Comment by adamdecaf** [comment]
I'm :+1: On https://github.com/Banno/banno-sbt-plugin/commit/f6a2117cf2c9582766f1e62e993b4a906c0134f8 though

**Comment by DustinChaloupka** [comment]
Oh, you're right. I had thought I fixed that somewhere, just had it locally and thought I forgot to push it. I'll remove it.

**Comment by DustinChaloupka** [comment]
Donezo.

**Comment by rubbish** [comment]
:+1:

**Comment by adamdecaf** [comment]
I fixed the title. :+1:

**Pull request merged**
