### PR TITLE
fix release-if-changed to bail on fail

### PR DESCRIPTION
**Pull request by rubbish**
I noticed on
https://jenkins.dev.banno-internal.com/job/internal-api%20release/1603/console
that even though the compile was failing it still pushed up the tag and
version info, however, it should've just failed. It turns out that the
failure handling might have changed between sbt versions.

So I upgraded us to the newest sbt-release and fixed the
problem. Unfortunately, sbt-release hides a lot of things so there was a
bit of copy pasta from it. :disappointed_relieved:

### CODE REVIEW

**Comment by adamdecaf** [comment]
:+1:

**Comment by adamdecaf** [comment]
Can we add a note to the changelog about this version bump?

**Comment by rubbish** [comment]
ah yes

**Comment by rubbish** [comment]
@adamdecaf done

**Comment by DustinChaloupka** [comment]
:+1:

**Pull request merged**
