### PR TITLE
Publish scaladocs

### PR DESCRIPTION
**Pull request by adamdecaf**

### CODE REVIEW

**Comment by adamdecaf** [comment]
@trentio @zmccoy Can you check out this also?

**Comment by zmccoy** [comment]
LGTM :cat2:

**Comment by zmccoy** [comment]
For reference to anyone if they don't know what this is doing: http://www.scala-sbt.org/0.12.2/docs/Detailed-Topics/Artifacts.html

**Comment by rubbish** [comment]
So we publish the scaladocs, how do we access them?

**Comment by adamdecaf** [comment]
I wonder if we could override the publish step for scaladocs to push to S3. Then we could split them out and have one end point for them.

S3:

docs.banno-internal.com/
  /app1
    /index.html
  /app2
    /index.html

**Comment by rubbish** [comment]
i wonder if nexus or artifactory has support for reading javadocs/scaladocs

**Comment by adamdecaf** [comment]
Or something something build docker image around docs and have the deployment of it be LATEST.

**Comment by adamdecaf** [comment]
I'm not sure how typesafe does it, but I think they just have a cron that runs for their "nightly" that pulls from their repos.

It just published up a jar http://repo.spray.io/io/spray/spray-can/1.3.1/

**Pull request merged**
