### PR TITLE
java 8 removed MaxPermSize

### PR DESCRIPTION
**Pull request by sherzberg**
this removes a startup warning

* http://stackoverflow.com/a/22634689
* http://stackoverflow.com/a/18345876

### CODE REVIEW

**Comment by adamdecaf** [comment]
:+1: Can we update the changelog?

**Comment by sherzberg** [comment]
@adamdecaf manually? or do we have a tool to do this?

**Comment by sherzberg** [comment]
Can we also be explicit about setting the java:8 docker image instead of latest?

**Comment by adamdecaf** [comment]
@sherzberg it's just a markdown file https://github.com/Banno/banno-sbt-plugin/blob/master/CHANGELOG.md

**Pull request merged**
