### PR TITLE
frequently running out of memory while repeatedly testing because resour...

### PR DESCRIPTION
**Pull request by guesswho311**
...ces are generated upon compile every time, added this in so projects can specify if they want settings that apply on compile or just on run

### CODE REVIEW

**Comment by guesswho311** [comment]
thoughts?

**Comment by adamdecaf** [comment]
I think if anything it should be a `SettingKey[Boolean]` that is just read in each object. I don't use `~compile` or spray-revolver so I don't run into this issue.

**Comment by guesswho311** [comment]
I'm not sure I understand. 

This becomes an issue, mostly just with Grunt.settings, whenever you compile, run, or test code(as long as a change was made). I made this to speed up testing when the generated resources are unnecessary.

**Comment by adamdecaf** [comment]
Compiling and running grunt is needed though.

**Comment by guesswho311** [comment]
I'm not sure if its necessary during testing(for some projects not all of them) though

**Comment by guesswho311** [comment]
I had insufficient memory allocated to sbt which was the main problem. I'm closing this PR unless people think it could be useful for other reasons.

**Comment by hoff2** [comment]
I've had this problem and thought it was just a bug with sbt or scalac

**Pull request closed without merging**
