### PR TITLE
allow the buildTime field in BuildInfo to be disabled

### PR DESCRIPTION
**Pull request by adamdecaf**

### CODE REVIEW

**Comment by adamdecaf** [comment]
It might be better to give it some default value so apps don't potentially get a NoSuchMethod exception if some library assumes it's there.

**Comment by trentio** [comment]
What use is the build time?

**Comment by rubbish** [comment]
I would rather just remove it instead of hiding it behind a flag that never gets used

**Comment by adamdecaf** [comment]
Yea, maybe removing it is better.

**Pull request closed without merging**
