### PR TITLE
Removing big-kill & big-destroy since only big-up is used by addBigServices.

### PR DESCRIPTION
**Pull request by jwinder**
https://github.com/Banno/big/issues/326

### CODE REVIEW

**Comment by DustinChaloupka** [comment]
@jwinder I think we actually use the `big-destroy` in some jenkins jobs... at least I think so. When I tried to find an example quick I couldn't find one.... a lot of them are actually executing the shell version of it... so maybe this is fine?

**Comment by jwinder** [comment]
Nothing uses big-destroy from the sbt plugin that I know of.

**Comment by trentio** [comment]
:+1:

**Comment by trentio** [comment]
I think the tests might have failed because of the internet issues we were seeing.

**Comment by trentio** [comment]
retest this please

**Pull request merged**
