### PR TITLE
Most npm and bower flags are now set in Jenkins global config files

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
These are no longer needed as they are handled by Banno/jenkins-setup#36

### CODE REVIEW

**Comment by adamdecaf** [comment]
@ChadKillingsworth Would someone need these flags on their own jenkins setup?

**Comment by rubbish** [comment]
Or when building locally?

**Comment by ChadKillingsworth** [comment]
Currently, the registry is just being used as a proxy. I'm working on adding tooling setup to `big` for UX tools which will configure any dev's machine to properly trust our registry and use it for the correct installs.

I'll re-add the `--spin=false` flag, but I really want to remove the registry flag as it overwrites Jenkins use of the `https` version. I want to turn off `http` for npm.banno-internal.com.

**Comment by ChadKillingsworth** [comment]
Here's the big checks to see if the tools are properly installed and configured: banno/big#265

**Comment by rubbish** [comment]
:+1:

**Pull request merged**
